# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty

# Setup
title:            ''
tagline:          ''
description:      ''
url:              ''
baseurl:          /

author:
  name:           ''
  url:

paginate:         0

# Custom vars
version:          ''
github:           ''
  repo:           ''
