# Permalinks
permalink:        pretty

# Setup
title:         title
tagline:       tagline
description:   description
url:
baseurl:

author:        author
  name:
  url:

paginate:         0

# Custom vars
version:          version
github:           github
  repo:           repo
