# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ''
tagline:          ''
description:      ''
url:              ''
baseurl:          /

author:
  name:           ''
  url:

paginate:         0

# Custom vars
version:          2.1.0

github:
  repo:
